version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: MedCare_Local
    restart: always
    environment:
      MYSQL_DATABASE: MedCare
      MYSQL_ROOT_PASSWORD: admin123
    ports:
    - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: pharmacy_api
    ports:
    - "8000:8000"
    depends_on:
    - db
    environment:
      # Note: We use 'db' (the service name) instead of 'localhost'
      DATABASE_URL: mysql+pymysql://root:your_password@db:3306/MedCare
    volumes:
    - .:/app

volumes:
  db_data:
